name: RyanRobilliard
favicon: null
layout_spectrum: 0.49037
typography_spectrum: 0.5039
title: Ryan Robilliard Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050e0d'
    - '#eef0ef'
    - '#9d9d9b'
    - '#565c5a'
    - '#757b79'
  brandStrength: 0.8940350082702935
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
