name: RyanRobilliard
favicon: null
layout_spectrum: 0.6259911344386637
typography_spectrum: 0.6985070186201483
title: Ryan Robilliard Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8940350082702935
  lightness: 0.7631003954447806
  saturation: 0.2301389155909419
  rhythmicContrast: 0.4341182850766927
purpose: []
